### ISSUE TITLE
AttributeError: type object 'ExistingCountries' has no attribute 'data_class_base'

### ISSUE THREAD

**Issue by JavierParada** [xmba15/gadm#10]
I received this error message when I tried to run
<img width="896" alt="Screenshot 2023-12-13 at 3 00 58 PM" src="https://github.com/xmba15/gadm/assets/38672862/10f86242-bfbd-4d7d-bbd4-f11d6c19be40">
 your first example.

**Comment by xmba15** [comment]
@JavierParada Can you please share the info about your environment (e.g. python version,...) and also `pycountry`'s version
```python
import pycountry as pct
print(pct.__version__)
```

**Comment by xmba15** [comment]
I released a fix for `gadm`. Can you try with gadm's v0.0.5 version?

**Comment by JavierParada** [comment]
I tried it again and it works. Thanks!
